# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TileNetworkOrder
                                 A QGIS plugin
 Tile Network Order plugin generates Ordering ID, Burying Depths, Flow Direction etc.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-28
        copyright            : (C) 2022 by FALASY  Anamelechi
        email                : fvw.services@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TileNetworkOrder class from file TileNetworkOrder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tile_network_order import TileNetworkOrder
    return TileNetworkOrder(iface)
